### ISSUE TITLE
Milestone 3 objectives

### ISSUE THREAD

**Issue by topspinj** [UBC-MDS/PyPunisher#61]
### General
- set up Travis ✅ 
- add Software License ✅ 
- show branch coverage  ✅

### PyPunisher
- exception handling ✅ 
- integration tests  ✅
- render docs ✅
- add example to README ✅

### punisheR
- exception handling ✅  
- integration tests   ✅
- make package name consistent (punisheR vs punishR) ✅ 
- ~~explore formatR (time permitting)~~

### Issues in punisheR
- Test whether forward and backward work for returning multiple features ✅ 
- Better test for values from AIC & BIC ✅ 
- Potential spelling errors identified by `devtools::spell_check()` ✅ 
- Suggested issues from the `goodpractice` package ✅  [goodpractice() now passing with 0 errors/warnings]
- `covr` suggests you are not at 100% branch coverage ✅  [100% coverage achieved]
- notes to address from running devtools::check() ✅ 
- no explanation of what the `test_data` function does in vignette  ✅
- Add example of functions in README  ✅
- Vignette not rendered in repo ✅ 
- require matrix and vectors as input for `forward` and `backward` functions? ✅ 
- Function documentation incomplete  ✅
- Additions to how this package fits into the existing R ecosystem ✅ 

### Bonus
- implement linter in our CI pipeline ✅

**Comment by avinashkz** [comment]
### Issues to resolve in punisheR

* Test whether forward and backward work for returning multiple features

* Better test for values from AIC & BIC

* Potential spelling errors identified by `devtools::spell_check()`

* Suggested issues from the `goodpractice` package

* `covr` suggests you are not at 100% branch coverage

* notes to address from running devtools::check()

* no explanation of what the `test_data` function does in vignette

* Add example of functions in README

* Vignette not rendered in repo

* require matrix and vectors as input for `forward` and `backward` functions?

* Function documentation incomplete

* Additions to how this package fits into the existing R ecosystem
