### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by arthursunbao** [UBC-MDS/PyPunisher#62]
Hi All,

Nice work for milestone 2. I like your comprehensive designs for the entire package. Here is my comments:

1. Good Practice to state out installation requires python 3.6

2. I like your coverage part to detail your test coverage, excellent

3. For __init__.py, line 4 and 5, why not just list.append() to have version number?

4. For selection_engines/__init__.py, I like your comments for the issue in scipy

5. Please improve your style in Python programming, you can refer to https://google.github.io/styleguide/pyguide.html  as in selection.py line 4, this is not professional, also the space you have between lines are not equal.

6. For your first line of your python file, it is suggested that you can include #!/usr/bin/env python just in case the user is running your code in Linux(like me)

7. for _fit_and_score(self, S, feature, algorithm), what if algorithm input is wrong input parameters? if you thought about that?

8. For function backward(), S is not a good naming for a list

Regards
Jason

**Comment by TariqAHassan** [comment]
@arthursunbao

The line you are seeing is for `sphinx`, which you can check out here: http://www.sphinx-doc.org/en/master/.

**Comment by arthursunbao** [comment]
@TariqAHassan 

I have no issue regarding your question 8 since you found that from your presentation in 573. But it is still not recommended in industry usage 

For Q3, I understand.

**Comment by TariqAHassan** [comment]
@arthursunbao 

Hi.

Are 4 and 7 OK?

**Comment by arthursunbao** [comment]
Yup. I see your point for now


2018-03-16 21:05 GMT-07:00 Tariq Hassan <notifications@github.com>:

**Comment by TariqAHassan** [comment]
@arthursunbao 

Great. Thanks!
