### ISSUE TITLE
More feedback on milestone 2

### ISSUE THREAD

**Issue by meghanallen** [UBC-MDS/PyPunisher#64]
Overall, very well done.

Each of your test cases should be in its own test function that is named in a descriptive way. Then you can easily tell which test case has failed when you get failures.

The requirement was to show that your tests provide 100% branch coverage but you have provided the statement coverage. See https://github.ubc.ca/ubc-mds-2017/DSCI_524_collab-sw-dev_students/issues/9 for more info.

Please fix both of these issues before the next milestone.

**Comment by topspinj** [comment]
(originally posted this in the wrong repo, sorry!)

Hi Meghan, we have a lot of logic in our functions that will make it very hard to prove each condition gets executed (unless you use print statements). For example, in our [forward selection function](https://github.com/UBC-MDS/PyPunisher/blob/master/pypunisher/selection_engines/selection.py#L150), lines 150-157,  we have the following code:

```
        for _ in worse_case:
            worse_case.set_postfix(n_features=len(S), score=best_score)
            # 1. Find best feature, j, to add.
            j_score_dict = dict()
            for j in itera:
                j_model_score = self._fit_and_score(S, feature=j, algorithm='forward')
                if best_score is None or (j_model_score > best_score):
                    j_score_dict[j] = j_model_score
```

This iterates through features of a dataset and checks to see if the score of that particular feature is better than the current `best_score`. If it is, `best_score` will get updated. 

What is the best way to tackle this particular scenario and prove that this "branch" is covered.

**Comment by meghanallen** [comment]
You don't need to "prove" it using a mathematical proof or by showing that a print statement is executed. Instead, you need to choose a test case that you believe will execute that code. 

You're aiming to have every feasible branch taken, so if it's not possible for worse_case to be empty (e.g. if your code would have previously raised an error if it was empty) then you don't need to test that branch.

For the if statement, you could choose input that you know will take the true branch at least once (I think that would be any input since I assume best_score is initialized to None) and the false branch at least once.

Let me know if you still have questions.

**Comment by TariqAHassan** [comment]
@meghanallen 

I do not understand how this would not commit us to bad practices.
While there are some cases where our tests should be broken up,
others would mandate we, essentially, run `for` loops by hand, violating D.R.Y.

For instance:

```
def test_metric_output_value():
    """Test that the actual AIC and BIC values computed by
    our functions match that computed by a well-respected
    statistical library in Python (StatsModels)."""
    for metric, comparision in zip((aic, bic), (sm_aic, sm_bic)):
        ours = metric(sk_model, X_train=X_train, y_train=y_train)
        test = ours == pytest.approx(comparision, abs=COMP_TOLERANCE)
        assert test, "`{}()` does not match the value from StatsModels.".format(
            metric.__name__
        )
```

The logic is the same for both `aic()` and `bic()`. Namely, we want to compare their yield to the well-respected `StatsModels` library for statistical analysis in Python. Breaking these up these kinds of operations into distinct functions is liable to introduce bugs in the code because, as I said above, we'd just be supplanting a `for` loop with a crude, manual solution.

Please let me know if I have misunderstood you.

**Comment by meghanallen** [comment]
I don't know what you mean by run for loops by hand. Could you explain?

**Comment by TariqAHassan** [comment]
@meghanallen 

Sure.

I mean it would be tantamount to running `for` loops by hand.

For instance, I could write:

```
for i in range(2, 8, 2):
    print(i ** 2)
```

Or this:

```
print(2 ** 2)
print(4 ** 2)
print(6 ** 2)
```

I want to avoid doing the latter.

**Comment by meghanallen** [comment]
I think you may have misunderstood my original comment because you don't need to do that. It's possible (and likely) that you'll have to have multiple tests for each of your functions. Which part of my feedback are you trying to work on that led you to this concern?

**Comment by TariqAHassan** [comment]
> Each of your test cases should be in its own test function that is named in a descriptive way.

We test (very related) test cases in loops in our `/tests` director, so I assumed that is what you were referencing. Were there specific tests that you thought were done incorrectly and need improvement?
